server:
  port: 8889
  name: consomer
spring:
  application:
    name: demo

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngapoutfotso@gmail.com
    password: yourPassWord
    passwords: yourPassWord
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      database: Nesletter
      host: localhost
      port: 27017
      auto-index-creation: true
    main:
      allow-bean-definition-overriding: true
